GAME_LOL = '11'
GAME_DOTA = '24'
GAME_KOG = '254'
GAME_CSGO = '205'

GAME_ID_LOL = 1  # 英雄联盟
GAME_ID_DOTA = 2  # DOTA2
GAME_ID_KOG = 3  # 王者荣耀
GAME_ID_CSGO = 4  # CS:GO
GAME_ID_LIST = {
    GAME_LOL: GAME_ID_LOL,
    GAME_DOTA: GAME_ID_DOTA,
    GAME_KOG: GAME_ID_KOG,
    GAME_CSGO: GAME_ID_CSGO
}

GAME_LIST = [
    '11',  # LOL
    '24',  # DOTA2
    '254',  # 王者荣耀
    '205'  # CSGO
]
