GAME_LOL = 'lol'
GAME_DOTA = 'dota'
GAME_KOG = 'kog'
GAME_CSGO = 'csgo'
GAME_LIST = [GAME_LOL, GAME_KOG, GAME_DOTA, GAME_CSGO]

GAME_ID_LOL = 1  # 英雄联盟
GAME_ID_DOTA = 2  # DOTA2
GAME_ID_KOG = 3  # 王者荣耀
GAME_ID_CSGO = 4  # CS:GO
GAME_ID_LIST = {
    GAME_LOL: GAME_ID_LOL,
    GAME_DOTA: GAME_ID_DOTA,
    GAME_KOG: GAME_ID_KOG,
    GAME_CSGO: GAME_ID_CSGO
}
